#! /usr/bin/python
import cgi

form = cgi.FieldStorage()
oper1 = int(form.getValue('oper1'))
oper2 = int(form.getValue('oper2'))

print('Content-Type: text/html; charset=utf-8\n\r\n\r')
print('<html><head><title>Test CGI</title></head><body><pre>'
+oper1
+'+'
+oper2
+'='
+oper1+oper2
+'</pre></body></html>')
